In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
train_data=pd.read_csv("/content/drive/MyDrive/Datasets/Delivery Time prediction dataset/train.csv")
test_data=pd.read_csv("/content/drive/MyDrive/Datasets/Delivery Time prediction dataset/test.csv")

In [4]:
len(train_data)

45593

In [6]:
len(test_data)

11399

In [7]:
train_data["label"]="Train"
test_data["label"]="Test"

In [8]:
df=pd.concat([train_data,test_data],axis=0)

In [9]:
df.shape

(56992, 21)

In [10]:
df.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,...,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min),label
0,0x4607,INDORES13DEL02,37,4.9,22.745049,75.892471,22.765049,75.912471,19-03-2022,11:30:00,...,conditions Sunny,High,2,Snack,motorcycle,0,No,Urban,(min) 24,Train
1,0xb379,BANGRES18DEL02,34,4.5,12.913041,77.683237,13.043041,77.813237,25-03-2022,19:45:00,...,conditions Stormy,Jam,2,Snack,scooter,1,No,Metropolitian,(min) 33,Train
2,0x5d6d,BANGRES19DEL01,23,4.4,12.914264,77.678400,12.924264,77.688400,19-03-2022,08:30:00,...,conditions Sandstorms,Low,0,Drinks,motorcycle,1,No,Urban,(min) 26,Train
3,0x7a6a,COIMBRES13DEL02,38,4.7,11.003669,76.976494,11.053669,77.026494,05-04-2022,18:00:00,...,conditions Sunny,Medium,0,Buffet,motorcycle,1,No,Metropolitian,(min) 21,Train
4,0x70a2,CHENRES12DEL01,32,4.6,12.972793,80.249982,13.012793,80.289982,26-03-2022,13:30:00,...,conditions Cloudy,High,1,Snack,scooter,1,No,Metropolitian,(min) 30,Train

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 56992 entries, 0 to 11398
Data columns (total 21 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           56992 non-null  object
 1   Delivery_person_ID           56992 non-null  object
 2   Delivery_person_Age          56992 non-null  object
 3   Delivery_person_Ratings      56992 non-null  object
 4   Restaurant_latitude          56992 non-null  float64
 5   Restaurant_longitude         56992 non-null  float64
 6   Delivery_location_latitude   56992 non-null  float64
 7   Delivery_location_longitude  56992 non-null  float64
 8   Order_Date                   56992 non-null  object
 9   Time_Orderd                  56992 non-null  object
 10  Time_Order_picked            56992 non-null  object
 11  Weatherconditions            56992 non-null  object
 12  Road_traffic_density         56992 non-null  object
 13  Vehicle_condition            56992 non-null  int64
 14  Type_of_order                56992 non-null  object
 15  Type_of_vehicle              56992 non-null  object
 16  multiple_deliveries          56992 non-null  object
 17  Festival                     56992 non-null  object
 18  City                         56992 non-null  object
 19  Time_taken(min)              45593 non-null  object
 20  label                        56992 non-null  object
dtypes: float64(4), int64(1), object(16)
memory usage: 9.6+ MB

In [12]:
df=df.rename(columns={"Time_taken(min)":"Time_taken"})

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 56992 entries, 0 to 11398
Data columns (total 21 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           56992 non-null  object
 1   Delivery_person_ID           56992 non-null  object
 2   Delivery_person_Age          56992 non-null  object
 3   Delivery_person_Ratings      56992 non-null  object
 4   Restaurant_latitude          56992 non-null  float64
 5   Restaurant_longitude         56992 non-null  float64
 6   Delivery_location_latitude   56992 non-null  float64
 7   Delivery_location_longitude  56992 non-null  float64
 8   Order_Date                   56992 non-null  object
 9   Time_Orderd                  56992 non-null  object
 10  Time_Order_picked            56992 non-null  object
 11  Weatherconditions            56992 non-null  object
 12  Road_traffic_density         56992 non-null  object
 13  Vehicle_condition            56992 non-null  int64
 14  Type_of_order                56992 non-null  object
 15  Type_of_vehicle              56992 non-null  object
 16  multiple_deliveries          56992 non-null  object
 17  Festival                     56992 non-null  object
 18  City                         56992 non-null  object
 19  Time_taken                   45593 non-null  object
 20  label                        56992 non-null  object
dtypes: float64(4), int64(1), object(16)
memory usage: 9.6+ MB

In [14]:
df.isnull().sum()

ID                                 0
Delivery_person_ID                 0
Delivery_person_Age                0
Delivery_person_Ratings            0
Restaurant_latitude                0
Restaurant_longitude               0
Delivery_location_latitude         0
Delivery_location_longitude        0
Order_Date                         0
Time_Orderd                        0
Time_Order_picked                  0
Weatherconditions                  0
Road_traffic_density               0
Vehicle_condition                  0
Type_of_order                      0
Type_of_vehicle                    0
multiple_deliveries                0
Festival                           0
City                               0
Time_taken                     11399
label                              0
dtype: int64

In [19]:
df.tail(1)

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,...,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken,label
11398,0xb7be,CHENRES07DEL02,39,5,13.081878,80.248519,13.131878,80.298519,24-03-2022,22:20:00,...,conditions Windy,Low,2,Drinks,motorcycle,1,No,Urban,NaN,Test

In [28]:
df["Time_taken"].unique()

array(['(min) 24', '(min) 33', '(min) 26', '(min) 21', '(min) 30',
       '(min) 40', '(min) 32', '(min) 34', '(min) 46', '(min) 23',
       '(min) 20', '(min) 41', '(min) 15', '(min) 36', '(min) 39',
       '(min) 18', '(min) 38', '(min) 47', '(min) 12', '(min) 22',
       '(min) 25', '(min) 35', '(min) 10', '(min) 19', '(min) 11',
       '(min) 28', '(min) 52', '(min) 16', '(min) 27', '(min) 49',
       '(min) 17', '(min) 14', '(min) 37', '(min) 44', '(min) 42',
       '(min) 31', '(min) 13', '(min) 29', '(min) 50', '(min) 43',
       '(min) 48', '(min) 54', '(min) 53', '(min) 45', '(min) 51', nan],
      dtype=object)

In [34]:
for i in df.columns:
  print(i,df[i].unique())
  print("<>"*20)

ID ['0x4607 ' '0xb379 ' '0x5d6d ' ... '0x1ea5 ' '0x22d4 ' '0xb7be ']
<><><><><><><><><><><><><><><><><><><><>
Delivery_person_ID ['INDORES13DEL02 ' 'BANGRES18DEL02 ' 'BANGRES19DEL01 ' ...
 'KOCRES04DEL01 ' 'BHPRES06DEL03 ' 'GOARES03DEL03 ']
<><><><><><><><><><><><><><><><><><><><>
Delivery_person_Age ['37' '34' '23' '38' '32' '22' '33' '35' '36' '21' '24' '29' '25' '31'
 '27' '26' '20' 'NaN ' '28' '39' '30' '15' '50']
<><><><><><><><><><><><><><><><><><><><>
Delivery_person_Ratings ['4.9' '4.5' '4.4' '4.7' '4.6' '4.8' '4.2' '4.3' '4' '4.1' '5' '3.5'
 'NaN ' '3.8' '3.9' '3.7' '2.6' '2.5' '3.6' '3.1' '2.7' '1' '3.2' '3.3'
 '6' '3.4' '2.8' '2.9' '3']
<><><><><><><><><><><><><><><><><><><><>
Restaurant_latitude [ 22.745049  12.913041  12.914264  11.003669  12.972793  17.431668
  23.369746  12.352058  17.433809  30.327968  10.003064  18.56245
  30.899584  26.463504  19.176269  12.311072  18.592718  17.426228
  22.552672  18.563934  23.357804  12.986047  19.221315  13.005801
  26.849596  21.160522  12.934179  18.51421   11.022477  21.160437
  15.51315   15.561295   0.        18.55144   18.593481  21.173343
  17.451976  12.972532  13.064181  19.121999  21.149569  19.091458
  22.539129  12.970324  21.175975  11.003681  10.96185   27.165108
  26.88842   26.913987  12.3085    21.183434  19.254567  25.449659
  30.372202  21.157735  21.186438  12.935662  17.431477  12.933298
  22.311358  12.934365  13.086438  26.913483  17.411028  18.516216
  15.5696    19.876428  12.939496  23.374878 -27.163303  22.74806
  26.891191  12.316967  18.927584  11.022298  12.325461  18.530963
  17.458998  19.1813    22.727021  12.979166  18.994237  12.284747
  11.000762  26.479108  21.175104  12.975377  23.359194  12.297954
  23.359407  23.416792  26.892312  22.31279   22.761593  11.026117
  26.483042  23.359033  22.569358  21.157729  22.311603  18.536562
  22.745536  18.543626  17.41233   21.17106   21.186884  19.065838
  12.98041   12.310972  11.025083  22.538731  11.001753  22.310237
  22.725748  17.450851  13.081878  10.035573  22.308096  12.975996
  19.178321  26.910262  25.443994  12.321214  19.055831  12.337928
  23.351489  22.728163  13.026286  26.766536  21.149834  21.149669
  26.482581  26.911378  13.02978   12.323194  22.569367  12.949934
  22.725835  30.89286   12.933284  17.429585  12.978453  13.044694
  26.846156  26.911927  10.020683  15.585658  22.310526  19.103249
  26.471617  19.866969  12.906229  22.751857  11.010375  17.483216
  27.160934  11.006686  25.457687  19.12663   19.875016  18.536718
  13.026279  17.455894  13.054347  12.979096  27.163303  26.482419
  22.307898  27.160832  10.027014  30.890184  21.15276   22.753839
  19.876106  30.328174  13.058616 -27.165108  21.170096  30.905562
 -18.55144   26.902328  26.90519   17.428294  12.323978  26.492106
  19.003517  10.994136  23.353783  17.440827  12.304569  12.299524
  19.131141  19.879631  18.520016  21.170798  22.760072  22.761226
  23.354422  22.722634  12.972161  22.526461  23.371292  13.029198
  18.546258  26.921411  11.008638  13.049645  17.430448  19.874733
  13.045479  26.956431  13.022394  22.75004   21.173493  13.091809
  18.533811  15.496162  26.913726  30.895817 -30.366322  12.323994
  19.120083  12.337978  27.161661  13.066762  30.362686  17.410371
   9.979186  18.539299  22.310329  11.022169  19.875908  10.006881
  12.326356  19.875522  22.552996  30.895204  25.450329  18.546947
  30.340722  22.651847  25.45235   17.424114  12.323225 -12.325461
  26.905287  17.422819  17.45971   22.695207  18.569156  11.003008
  26.914142  30.359722  12.334022  23.214294 -12.316967  12.970221
  22.753659  18.636215  22.751234  23.234249  25.457116  22.744648
  23.39925   19.874103  22.577821  22.514119  22.311844  18.994049
  22.732225  30.914057  23.233219  12.981615  23.184992  26.49095
  22.551084  11.021278  30.899992  11.024839  23.351058  19.876219
  19.880256  13.027018  30.893234  30.319528  27.195928 -23.359194
  25.450317  21.185047  23.355164  23.232537  18.53408   26.902908
  11.016298  10.000706  25.454697  21.186608  26.90294   23.214459
  23.374989  30.893244  30.885915  17.438263  15.544419  26.474986
   9.970717  30.873988  19.888716  22.547186  23.232357  23.234631
  19.1093    22.32     -26.47775   26.469003  26.483672  10.027364
 -15.546594  19.207222  19.874449 -12.337978  11.02091   19.22384
  30.366322  30.361281  26.473698  18.554382  22.553227 -27.160934
  30.332735   9.982834  15.498603  22.5491    25.450377  26.471529
 -26.90519   23.218998  23.235123  22.533662  30.885814 -17.45971
  15.574828  25.459775  30.893081  22.514688 -26.914142  23.266261
  23.333017 -19.176269  27.157772  15.516833  22.527893  27.159795
  15.546594  15.157944  27.16185   30.88722   27.158822 -23.230791
  23.264015  27.161694   9.991703  27.201725   9.960846  26.481547
 -22.539129  15.303897   9.988483  25.454648  30.342509 -15.157944
  22.53796   -9.959778  30.346994 -15.51315   15.49395  -27.16185
  11.001852  30.893384 -15.576683  19.875337 -18.520016  15.556561
  23.230791 -26.891191  15.56155   30.335259 -22.538999  26.47775
 -19.103249 -30.902872   9.985497  25.451517 -22.526461  26.472001
   9.959778  -9.988483 -23.211529  30.892978  15.506205  19.878028
 -30.895817 -26.474986  22.538999   9.957144  22.515082  25.451646
 -15.5696   -12.311072 -26.913987 -12.970324   9.979363  10.028047
 -21.157735 -23.374989 -13.049645  26.474133  30.902872   9.985697
 -26.913726  23.211529  19.876994 -22.310329 -23.234249  15.576683
  22.514585  25.449872  25.453436   9.966783 -25.45235  -17.451976
 -21.186884 -26.472001 -26.910262 -11.003681 -11.003669 -13.054347
 -30.372202 -12.972793 -25.449872 -18.569156 -18.546258 -17.429585
 -27.159795 -22.553227 -22.761593  -9.966783 -13.086438 -19.878028
 -17.440827  -9.970717 -12.913041 -12.970221 -19.876994 -19.875522
 -25.449659 -30.346994 -22.552672 -22.311603 -12.352058 -25.450317
 -21.15276  -12.949934 -26.49095  -25.443994 -30.319528 -10.028047
 -12.323978 -19.876106  26.47     -18.53408  -26.463504 -30.899584
 -22.311844 -17.438263 -23.39925  -23.234631 -30.361281 -19.091458
 -17.483216 -15.496162 -22.725835 -30.885915 -22.53796  -12.972161
 -23.184992 -17.424114 -10.035573 -19.22384  -23.235123 -25.453436
 -23.359033 -19.221315 -23.214459 -21.173343 -26.483042 -21.183434
 -22.310526 -22.74806  -12.304569 -19.1093   -19.879631 -19.874449
 -10.020683 -19.875337 -26.911927 -23.416792 -21.186608 -12.323994
 -12.933284 -17.450851 -19.875016 -22.569358 -12.284747 -23.355164
 -18.592718 -27.201725 -22.311358 -19.207222 -13.022394 -21.149569
 -22.538731 -27.161661 -27.160832 -13.066762 -10.96185  -12.935662
 -17.428294 -30.359722 -11.022169 -30.885814 -25.451517 -22.651847
 -22.547186 -26.474133 -30.893384 -22.761226 -11.001852 -30.327968
 -22.745536 -17.455894 -26.481547 -22.32     -23.371292 -18.563934
 -30.905562 -25.450377 -22.515082 -22.725748 -23.351058 -26.473698
 -23.333017 -30.873988  -9.982834 -22.514119 -21.170798 -12.979166
 -19.065838 -19.876428 -13.02978  -12.310972 -22.307898 -21.170096
 -21.186438  -9.960846 -10.994136 -21.175104 -15.303897 -11.022477
 -26.846156 -25.457116 -26.905287 -21.149834 -30.328174 -30.362686
 -19.055831 -22.5491   -26.471529 -12.934365 -30.893244 -19.888716
 -12.975377 -22.551084 -15.561295 -22.695207 -26.956431  -9.979186
 -11.006686 -12.323225 -13.026286 -25.454697 -23.357804 -19.880256
 -13.081878 -10.027014 -18.543626 -10.003064 -22.552996 -18.530963
 -19.866969 -22.75004  -26.469003 -26.766536 -12.326356 -22.577821
 -22.569367 -23.232357 -13.091809 -12.933298 -22.533662 -22.745049
 -26.921411 -23.374878 -27.158822 -12.906229 -13.044694 -13.045479
 -12.98041  -26.90294  -23.369746 -19.875908 -26.479108 -30.892978
 -23.232537 -22.514585 -22.751234 -17.426228 -17.411028 -18.636215
 -15.56155  -19.254567 -25.457687 -15.506205 -15.516833 -11.02091
 -12.3085   -26.47     -19.003517 -30.890184 -22.760072 -22.722634
 -19.12663  -22.753839 -21.173493 -17.430448 -12.939496 -18.56245
 -22.308096 -23.264015 -26.482581 -15.498603 -18.51421  -12.975996
 -19.874733 -15.49395  -12.978453 -11.026117 -11.016298 -26.492106
 -22.728163 -18.554382 -11.021278 -26.892312 -21.160437 -25.459775
 -11.000762 -25.451646 -22.310237 -15.574828 -12.334022 -11.001753
 -21.157729 -26.849596 -17.422819 -15.544419 -12.299524 -19.131141
 -17.41233  -30.340722 -17.458998 -19.120083 -12.979096 -18.539299
 -12.914264 -17.431668 -30.342509 -19.121999 -11.003008]
<><><><><><><><><><><><><><><><><><><><>
Restaurant_longitude [ 75.892471  77.683237  77.6784    76.976494  80.249982  78.408321
  85.33982   76.60665   78.386744  78.046106  76.307589  73.916619
  75.809346  80.372929  72.836721  76.654878  73.773572  78.407495
  88.352885  73.915367  85.325146  80.218114  72.862381  80.250744
  75.800512  72.771477  77.615797  73.838429  76.995667  72.774209
  73.78346   73.749478   0.        73.804855  73.785901  72.792731
  78.385883  77.608179  80.236442  72.908493  72.772697  72.827808
  88.365507  77.645748  72.795503  76.975525  76.971082  78.015053
  75.800689  75.752891  76.665808  72.814492  72.848923  81.839744
  78.077151  72.768778  72.794115  77.61413   78.40035   77.614293
  73.164798  77.616155  80.220672  75.803139  78.329645  73.842527
  73.742294  75.364792  77.625999  85.335739  78.057044  75.8934
  75.802083  76.603067  72.832585  76.998349  76.632278  73.828972
  78.500366  72.836191  75.884167  77.640709  72.825553  76.625861
  76.981876  80.315042  72.804342  77.696664  85.325447  76.665169
  85.325055  85.316842  75.806896  73.170283  75.886362  76.944652
  80.317833  85.325347  88.433452  72.768726  73.165012  73.896485
  75.893106  73.905101  78.449654  72.789292  72.793616  72.832658
  77.640489  76.659264  77.015393  88.364878  76.986241  73.158921
  75.898497  78.379347  80.248519  76.336958  73.167753  80.221898
  72.834715  75.783013  81.860187  76.621094  72.833984  76.617889
  85.324253  75.884212  80.275235  75.837333  72.778666  72.772629
  80.315628  75.789034  80.208812  76.630583  88.433187  77.699386
  75.887648  75.822199  77.615428  78.392621  77.643685  80.26147
  75.8023    75.797282  76.310631  73.743606  73.170937  72.846749
  80.313564  75.318894  77.596791  75.866699  76.95295   78.552111
  78.044095  76.951736  81.835585  72.829976  75.322405  73.830327
  80.174568  78.375467  80.257221  77.640625  80.320939  73.167788
  78.011608  76.308053  75.829615  72.778059  75.897429  75.340775
  78.049117  80.264151  72.789122  75.832841 -73.804855  75.794257
  75.810753  78.404423  76.627961  80.327797  72.82765   76.963303
  85.326967  78.393391  76.643622  76.64262   72.813074  75.323403
  73.830547  72.790489  75.892574  75.887522  85.3329    75.886959
  77.596014  88.364453  85.327872  77.570997  73.904337  75.793604
  76.984311  80.242268  78.418213  75.353942  80.23311   75.776649
  80.242439  75.902847  72.801953  80.219104  73.899315  73.825364
  75.75282   75.813112 -78.070453  76.626167  72.907385  76.616792
  78.011544  80.251865  78.06889   78.437225  76.317361  73.897902
  73.169083  76.999594  75.358888  76.345397  76.619103  75.367127
  88.35231   75.822103  81.834279  73.900626  78.060221  75.881991
  81.841889  78.347554  76.630028 -76.632278  75.794592  78.449578
  78.368855  75.866059  73.774723  76.97544   75.805704  78.067079
  76.618203  77.435361  77.645396  75.903365  73.751081  75.88949
  77.434007  81.859682  75.894377  85.390464  75.368419  88.400581
  88.362504  73.165081  72.825203  75.874765  75.83982   77.433571
  80.231598  77.417227  80.318656  88.354127  76.995017  75.831338
  77.007003  85.325731  75.346017  75.323503  80.254791  75.82172
  78.040267  77.998092 -85.325447  81.831681  72.80859   85.324097
  77.429845  73.89852   75.792934  76.972076  76.349516  81.834492
  72.794136  75.793007  77.434976  85.335486  75.821817  75.788259
  78.397865  73.755736  80.342796  76.285447  75.842739  75.321461
  88.35068   77.429989  77.401663  72.825451  73.17     -80.351569
  80.316344  80.320708  76.308258  73.760431  72.972281  75.360232
  76.940432  72.841347  78.070453  78.068022  80.352677  73.798206
  88.353273 -78.044095  78.054222  76.283268  73.826911  88.400467
  81.834236  80.313458 -75.810753  77.373573  77.398886  88.366217
  75.786976  73.766883  81.834841  75.821495  88.393294  77.379605
  85.3172   -72.836721  78.04725   73.768172  88.368628  78.04299
  73.950889  78.040165  75.804893  78.045359  77.43702   77.408236
  78.034714  76.293136  78.007553  76.293936  80.299775  73.914336
  76.295211  81.834502  78.061187  88.349843  76.296106  78.062543
  73.827423 -78.040165  76.976268  75.821202  73.75575   75.316722
 -73.830547  73.763633  73.749092  78.053162 -88.322337  80.351569
 -72.846749  75.826808  76.276999  81.832616  80.354002  77.419399
  75.821847  73.766668  75.317475  88.322337  76.296783  88.36783
  81.832796 -76.654878 -77.645748  76.285001  76.310019 -80.242268
  80.3481    76.281128  75.372353 -73.169083 -77.434007  88.39331
  81.836167  81.833167  76.242981 -81.841889 -78.385883 -75.783013
 -76.975525 -76.976494 -80.257221 -78.077151 -73.904337 -78.392621
 -78.04299  -75.367127 -78.062543 -88.352885 -76.60665  -77.699386
 -81.860187  80.35     -73.165081 -78.397865 -72.827808 -75.887648
 -85.335486 -77.596014 -78.347554 -72.841347 -72.862381 -72.792731
 -72.814492 -76.643622 -85.316842 -76.626167 -77.615428 -78.379347
 -76.625861 -73.164798 -72.972281 -77.683237 -78.011544 -80.251865
 -77.61413  -88.349843 -76.999594 -75.881991 -75.821202 -75.887522
 -76.976268 -78.375467 -73.17     -75.832841 -81.834236 -85.325731
 -85.3172   -76.283268 -77.640709 -78.068022 -80.208812 -72.789122
 -75.340775 -72.804342 -76.995667 -81.859682 -75.794592 -78.06889
 -76.963303 -77.616155 -77.696664 -75.866059 -76.951736 -76.630028
 -85.325146 -73.828972 -75.902847 -80.316344 -76.619103 -80.242439
 -76.293936 -77.614293 -88.366217 -75.837333 -75.892471 -75.793604
 -80.248519 -78.045359 -77.596791 -80.26147  -80.23311  -77.640489
 -80.220672 -75.793007 -85.33982  -78.407495 -73.773572 -76.603067
 -73.751081 -76.971082 -75.75282  -78.404423 -76.940432 -76.665808
 -73.742294 -77.43702  -75.829615 -72.772697 -75.897429 -80.318656
 -72.801953 -72.832658 -73.916619 -77.408236 -73.838429 -72.778059
 -73.827423 -77.643685 -78.011608 -88.364453 -85.327872 -80.327797
 -73.798206 -88.400467 -78.007553 -76.995017 -80.219104 -75.806896
 -81.834841 -73.78346  -73.766883 -88.36783  -73.915367 -76.317361
 -72.768726 -75.800512 -81.839744 -76.64262  -78.449654 -75.802083
 -72.907385 -77.401663 -73.897902 -77.6784   -78.061187 -76.97544 ]
<><><><><><><><><><><><><><><><><><><><>
Delivery_location_latitude [22.765049 13.043041 12.924264 ... 20.005337 25.460377 30.903988]
<><><><><><><><><><><><><><><><><><><><>
Delivery_location_longitude [75.912471 77.813237 77.6884   ... 75.446722 81.844236 75.872739]
<><><><><><><><><><><><><><><><><><><><>
Order_Date ['19-03-2022' '25-03-2022' '05-04-2022' '26-03-2022' '11-03-2022'
 '04-03-2022' '14-03-2022' '20-03-2022' '12-02-2022' '13-02-2022'
 '14-02-2022' '02-04-2022' '01-03-2022' '16-03-2022' '15-02-2022'
 '10-03-2022' '27-03-2022' '12-03-2022' '01-04-2022' '05-03-2022'
 '11-02-2022' '08-03-2022' '03-04-2022' '30-03-2022' '28-03-2022'
 '18-03-2022' '06-04-2022' '04-04-2022' '24-03-2022' '09-03-2022'
 '02-03-2022' '13-03-2022' '29-03-2022' '31-03-2022' '17-03-2022'
 '07-03-2022' '15-03-2022' '16-02-2022' '03-03-2022' '18-02-2022'
 '23-03-2022' '17-02-2022' '06-03-2022' '21-03-2022']
<><><><><><><><><><><><><><><><><><><><>
Time_Orderd ['11:30:00' '19:45:00' '08:30:00' '18:00:00' '13:30:00' '21:20:00'
 '19:15:00' '17:25:00' '20:55:00' '21:55:00' '14:55:00' '17:30:00'
 '09:20:00' '19:50:00' '20:25:00' '20:30:00' '20:40:00' '21:15:00'
 '20:20:00' '22:30:00' '08:15:00' '19:30:00' '12:25:00' '18:35:00'
 '20:35:00' '23:20:00' '23:35:00' '22:35:00' '23:25:00' '13:35:00'
 '21:35:00' '18:55:00' '14:15:00' '11:00:00' '09:45:00' '08:40:00'
 '23:00:00' 'NaN ' '19:10:00' '10:55:00' '21:40:00' '19:00:00' '16:45:00'
 '15:10:00' '22:45:00' '22:10:00' '20:45:00' '22:50:00' '17:55:00'
 '09:25:00' '20:15:00' '22:25:00' '22:40:00' '23:50:00' '15:25:00'
 '10:20:00' '10:40:00' '15:55:00' '20:10:00' '12:10:00' '15:30:00'
 '10:35:00' '21:10:00' '20:50:00' '12:35:00' '21:00:00' '23:40:00'
 '18:15:00' '18:20:00' '11:45:00' '12:45:00' '23:30:00' '10:50:00'
 '21:25:00' '10:10:00' '17:50:00' '22:20:00' '12:40:00' '23:55:00'
 '10:25:00' '08:45:00' '23:45:00' '19:55:00' '22:15:00' '23:10:00'
 '09:15:00' '18:25:00' '18:45:00' '16:50:00' '00:00:00' '14:20:00'
 '10:15:00' '08:50:00' '09:00:00' '17:45:00' '16:35:00' '21:45:00'
 '19:40:00' '14:50:00' '18:10:00' '12:20:00' '12:50:00' '09:10:00'
 '12:30:00' '17:10:00' '17:20:00' '18:30:00' '13:10:00' '19:35:00'
 '09:50:00' '15:00:00' '20:00:00' '10:30:00' '09:40:00' '15:35:00'
 '16:55:00' '22:55:00' '16:00:00' '17:15:00' '21:30:00' '18:40:00'
 '11:10:00' '13:50:00' '10:00:00' '21:50:00' '11:50:00' '22:00:00'
 '08:25:00' '11:20:00' '11:55:00' '09:30:00' '08:20:00' '08:10:00'
 '11:40:00' '23:15:00' '19:20:00' '12:15:00' '11:35:00' '11:15:00'
 '17:35:00' '17:40:00' '14:40:00' '18:50:00' '11:25:00' '14:25:00'
 '12:00:00' '16:10:00' '19:25:00' '08:55:00' '13:40:00' '17:00:00'
 '09:35:00' '08:35:00' '16:15:00' '13:20:00' '15:50:00' '15:20:00'
 '16:20:00' '14:30:00' '15:45:00' '16:40:00' '13:00:00' '12:55:00'
 '10:45:00' '13:25:00' '09:55:00' '15:15:00' '13:15:00' '14:00:00'
 '15:40:00' '16:25:00' '14:10:00' '13:45:00' '13:55:00' '14:35:00'
 '16:30:00' '14:45:00']
<><><><><><><><><><><><><><><><><><><><>
Time_Order_picked ['11:45:00' '19:50:00' '08:45:00' '18:10:00' '13:45:00' '21:30:00'
 '19:30:00' '17:30:00' '21:05:00' '22:10:00' '15:05:00' '17:40:00'
 '09:30:00' '20:05:00' '20:35:00' '15:10:00' '20:40:00' '20:50:00'
 '20:25:00' '22:45:00' '08:30:00' '19:45:00' '12:30:00' '18:50:00'
 '23:30:00' '21:35:00' '23:45:00' '22:50:00' '22:40:00' '23:35:00'
 '13:40:00' '21:45:00' '19:10:00' '14:25:00' '11:10:00' '09:55:00'
 '08:55:00' '23:10:00' '18:35:00' '19:25:00' '11:00:00' '19:15:00'
 '16:55:00' '11:40:00' '15:15:00' '22:55:00' '22:25:00' '20:55:00'
 '23:05:00' '18:00:00' '23:00:00' '09:40:00' '20:20:00' '22:35:00'
 '22:00:00' '23:55:00' '15:40:00' '10:30:00' '21:00:00' '10:50:00'
 '16:05:00' '20:15:00' '12:15:00' '15:45:00' '22:15:00' '10:45:00'
 '15:30:00' '00:05:00' '21:25:00' '12:45:00' '21:15:00' '18:20:00'
 '18:25:00' '11:50:00' '12:50:00' '10:55:00' '21:40:00' '10:20:00'
 '17:55:00' '23:50:00' '12:55:00' '00:10:00' '10:40:00' '09:00:00'
 '20:45:00' '20:00:00' '23:15:00' '22:20:00' '17:00:00' '00:15:00'
 '21:20:00' '14:35:00' '10:25:00' '09:05:00' '16:50:00' '08:40:00'
 '23:40:00' '21:50:00' '19:55:00' '15:00:00' '10:35:00' '09:25:00'
 '17:20:00' '17:25:00' '20:10:00' '00:00:00' '17:35:00' '19:00:00'
 '19:05:00' '13:20:00' '17:50:00' '18:05:00' '19:20:00' '10:05:00'
 '09:10:00' '21:55:00' '19:40:00' '09:50:00' '15:50:00' '18:30:00'
 '18:15:00' '16:15:00' '11:15:00' '21:10:00' '22:30:00' '15:20:00'
 '18:40:00' '23:20:00' '11:25:00' '13:55:00' '18:45:00' '22:05:00'
 '11:55:00' '18:55:00' '09:45:00' '17:15:00' '12:05:00' '12:00:00'
 '19:35:00' '08:25:00' '11:05:00' '15:35:00' '12:40:00' '12:25:00'
 '08:20:00' '23:25:00' '16:10:00' '08:15:00' '20:30:00' '13:00:00'
 '11:20:00' '08:50:00' '14:45:00' '17:45:00' '10:00:00' '08:35:00'
 '12:10:00' '11:35:00' '14:30:00' '10:15:00' '17:05:00' '10:10:00'
 '09:35:00' '11:30:00' '16:25:00' '09:15:00' '13:35:00' '15:55:00'
 '13:10:00' '13:05:00' '16:20:00' '16:30:00' '16:45:00' '09:20:00'
 '13:25:00' '14:15:00' '14:05:00' '16:35:00' '16:40:00' '13:30:00'
 '14:40:00' '12:20:00' '13:50:00' '17:10:00' '15:25:00' '14:20:00'
 '12:35:00' '14:00:00' '14:10:00' '14:55:00' '13:15:00' '14:50:00'
 '16:00:00']
<><><><><><><><><><><><><><><><><><><><>
Weatherconditions ['conditions Sunny' 'conditions Stormy' 'conditions Sandstorms'
 'conditions Cloudy' 'conditions Fog' 'conditions Windy' 'conditions NaN']
<><><><><><><><><><><><><><><><><><><><>

In [35]:
def nan_handling(x):
  if x=="NaN ":
    return np.nan
  else:
    return x

In [37]:
check_df=df.applymap(nan_handling)

<ipython-input-37-2137afa42173>:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  check_df=df.applymap(nan_handling)

In [39]:
df.isnull().sum()

ID                                 0
Delivery_person_ID                 0
Delivery_person_Age                0
Delivery_person_Ratings            0
Restaurant_latitude                0
Restaurant_longitude               0
Delivery_location_latitude         0
Delivery_location_longitude        0
Order_Date                         0
Time_Orderd                        0
Time_Order_picked                  0
Weatherconditions                  0
Road_traffic_density               0
Vehicle_condition                  0
Type_of_order                      0
Type_of_vehicle                    0
multiple_deliveries                0
Festival                           0
City                               0
Time_taken                     11399
label                              0
dtype: int64

In [38]:
check_df.isnull().sum()

ID                                 0
Delivery_person_ID                 0
Delivery_person_Age             2345
Delivery_person_Ratings         2415
Restaurant_latitude                0
Restaurant_longitude               0
Delivery_location_latitude         0
Delivery_location_longitude        0
Order_Date                         0
Time_Orderd                     2175
Time_Order_picked                  0
Weatherconditions                  0
Road_traffic_density             755
Vehicle_condition                  0
Type_of_order                      0
Type_of_vehicle                    0
multiple_deliveries             1231
Festival                         293
City                            1524
Time_taken                     11399
label                              0
dtype: int64

In [40]:
df=df.applymap(nan_handling)

<ipython-input-40-61cc25feacf0>:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df=df.applymap(nan_handling)

In [49]:
df.head(1)

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,...,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken,label
0,0x4607,INDORES13DEL02,37,4.9,22.745049,75.892471,22.765049,75.912471,19-03-2022,11:30:00,...,conditions Sunny,High,2,Snack,motorcycle,0,No,Urban,24,Train

In [46]:
df["Time_taken"]=df["Time_taken"].str.strip("(min)")

In [50]:
df.head(1)

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,...,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken,label
0,0x4607,INDORES13DEL02,37,4.9,22.745049,75.892471,22.765049,75.912471,19-03-2022,11:30:00,...,conditions Sunny,High,2,Snack,motorcycle,0,No,Urban,24,Train

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 56992 entries, 0 to 11398
Data columns (total 21 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           56992 non-null  object
 1   Delivery_person_ID           56992 non-null  object
 2   Delivery_person_Age          54647 non-null  object
 3   Delivery_person_Ratings      54577 non-null  object
 4   Restaurant_latitude          56992 non-null  float64
 5   Restaurant_longitude         56992 non-null  float64
 6   Delivery_location_latitude   56992 non-null  float64
 7   Delivery_location_longitude  56992 non-null  float64
 8   Order_Date                   56992 non-null  object
 9   Time_Orderd                  54817 non-null  object
 10  Time_Order_picked            56992 non-null  object
 11  Weatherconditions            56992 non-null  object
 12  Road_traffic_density         56237 non-null  object
 13  Vehicle_condition            56992 non-null  int64
 14  Type_of_order                56992 non-null  object
 15  Type_of_vehicle              56992 non-null  object
 16  multiple_deliveries          55761 non-null  object
 17  Festival                     56699 non-null  object
 18  City                         55468 non-null  object
 19  Time_taken                   45593 non-null  object
 20  label                        56992 non-null  object
dtypes: float64(4), int64(1), object(16)
memory usage: 9.6+ MB

In [51]:
df["Order_Date"]=pd.to_datetime(df["Order_Date"])
df["Time_Orderd"]=pd.to_datetime(df["Time_Orderd"])
df["Time_Order_picked"]=pd.to_datetime(df["Time_Order_picked"])

<ipython-input-51-1cc6a2f6c9c7>:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["Order_Date"]=pd.to_datetime(df["Order_Date"])
<ipython-input-51-1cc6a2f6c9c7>:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Time_Orderd"]=pd.to_datetime(df["Time_Orderd"])
<ipython-input-51-1cc6a2f6c9c7>:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Time_Order_picked"]=pd.to_datetime(df["Time_Order_picked"])

In [52]:
df["Day"]=df["Order_Date"].dt.day
df["Month"]=df["Order_Date"].dt.month
df["Year"]=df["Order_Date"].dt.year
df["Hour"]=df["Time_Orderd"].dt.hour
df["Minute"]=df["Time_Orderd"].dt.minute
df["Pick_Hour"]=df["Time_Order_picked"].dt.hour
df["Pick_Minute"]=df["Time_Order_picked"].dt.minute

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 56992 entries, 0 to 11398
Data columns (total 28 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           56992 non-null  object
 1   Delivery_person_ID           56992 non-null  object
 2   Delivery_person_Age          54647 non-null  object
 3   Delivery_person_Ratings      54577 non-null  object
 4   Restaurant_latitude          56992 non-null  float64
 5   Restaurant_longitude         56992 non-null  float64
 6   Delivery_location_latitude   56992 non-null  float64
 7   Delivery_location_longitude  56992 non-null  float64
 8   Order_Date                   56992 non-null  datetime64[ns]
 9   Time_Orderd                  54817 non-null  datetime64[ns]
 10  Time_Order_picked            56992 non-null  datetime64[ns]
 11  Weatherconditions            56992 non-null  object
 12  Road_traffic_density         56237 non-null  object
 13  Vehicle_condition            56992 non-null  int64
 14  Type_of_order                56992 non-null  object
 15  Type_of_vehicle              56992 non-null  object
 16  multiple_deliveries          55761 non-null  object
 17  Festival                     56699 non-null  object
 18  City                         55468 non-null  object
 19  Time_taken                   45593 non-null  object
 20  label                        56992 non-null  object
 21  Day                          56992 non-null  int32
 22  Month                        56992 non-null  int32
 23  Year                         56992 non-null  int32
 24  Hour                         54817 non-null  float64
 25  Minute                       54817 non-null  float64
 26  Pick_Hour                    56992 non-null  int32
 27  Pick_Minute                  56992 non-null  int32
dtypes: datetime64[ns](3), float64(6), int32(5), int64(1), object(13)
memory usage: 11.5+ MB

In [54]:
df.drop(["Order_Date","Time_Orderd","Time_Order_picked","ID","Delivery_person_ID"],axis=1,inplace=True)

In [55]:
df.shape

(56992, 23)

In [56]:
df.head()

,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,...,City,Time_taken,label,Day,Month,Year,Hour,Minute,Pick_Hour,Pick_Minute
0,37,4.9,22.745049,75.892471,22.765049,75.912471,conditions Sunny,High,2,Snack,...,Urban,24,Train,19,3,2022,11.0,30.0,11,45
1,34,4.5,12.913041,77.683237,13.043041,77.813237,conditions Stormy,Jam,2,Snack,...,Metropolitian,33,Train,25,3,2022,19.0,45.0,19,50
2,23,4.4,12.914264,77.678400,12.924264,77.688400,conditions Sandstorms,Low,0,Drinks,...,Urban,26,Train,19,3,2022,8.0,30.0,8,45
3,38,4.7,11.003669,76.976494,11.053669,77.026494,conditions Sunny,Medium,0,Buffet,...,Metropolitian,21,Train,5,4,2022,18.0,0.0,18,10
4,32,4.6,12.972793,80.249982,13.012793,80.289982,conditions Cloudy,High,1,Snack,...,Metropolitian,30,Train,26,3,2022,13.0,30.0,13,45

In [57]:
training_df=df[df["label"]=="Train"]
testing_df=df[df["label"]=="Test"]

In [61]:
training_df.drop("label",axis=1,inplace=True)
testing_df.drop("label",axis=1,inplace=True)

<ipython-input-61-bda5f706efba>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  training_df.drop("label",axis=1,inplace=True)
<ipython-input-61-bda5f706efba>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  testing_df.drop("label",axis=1,inplace=True)

In [62]:
## AS here the Datasets are ready for the preprocessing step

In [63]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [65]:
y=training_df["Time_taken"]
y

0         24
1         33
2         26
3         21
4         30
        ...
45588     32
45589     36
45590     16
45591     26
45592     36
Name: Time_taken, Length: 45593, dtype: object

In [66]:
x=training_df.drop("Time_taken",axis=1)

In [67]:
x.head()

,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,...,multiple_deliveries,Festival,City,Day,Month,Year,Hour,Minute,Pick_Hour,Pick_Minute
0,37,4.9,22.745049,75.892471,22.765049,75.912471,conditions Sunny,High,2,Snack,...,0,No,Urban,19,3,2022,11.0,30.0,11,45
1,34,4.5,12.913041,77.683237,13.043041,77.813237,conditions Stormy,Jam,2,Snack,...,1,No,Metropolitian,25,3,2022,19.0,45.0,19,50
2,23,4.4,12.914264,77.678400,12.924264,77.688400,conditions Sandstorms,Low,0,Drinks,...,1,No,Urban,19,3,2022,8.0,30.0,8,45
3,38,4.7,11.003669,76.976494,11.053669,77.026494,conditions Sunny,Medium,0,Buffet,...,1,No,Metropolitian,5,4,2022,18.0,0.0,18,10
4,32,4.6,12.972793,80.249982,13.012793,80.289982,conditions Cloudy,High,1,Snack,...,1,No,Metropolitian,26,3,2022,13.0,30.0,13,45

In [68]:
testing_df.shape

(11399, 22)

In [69]:
testing_df.drop("Time_taken",axis=1,inplace=True)

<ipython-input-69-3ef05d1ccb64>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  testing_df.drop("Time_taken",axis=1,inplace=True)

In [70]:
testing_df.shape

(11399, 21)

In [71]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [72]:
x_train.shape

(36474, 21)

In [73]:
y_train.shape

(36474,)

In [74]:
x_test.shape

(9119, 21)

In [75]:
y_test.shape

(9119,)

In [76]:
num_features=x_train.select_dtypes(include=["int64","float64"]).columns
cat_features=x_train.select_dtypes(include=["object"]).columns

In [77]:
num_features

Index(['Restaurant_latitude', 'Restaurant_longitude',
       'Delivery_location_latitude', 'Delivery_location_longitude',
       'Vehicle_condition', 'Hour', 'Minute'],
      dtype='object')

In [78]:
cat_features

Index(['Delivery_person_Age', 'Delivery_person_Ratings', 'Weatherconditions',
       'Road_traffic_density', 'Type_of_order', 'Type_of_vehicle',
       'multiple_deliveries', 'Festival', 'City'],
      dtype='object')

In [79]:
num_pipeline=Pipeline(steps=[
    ("imputer",SimpleImputer(strategy="median")),
    ("scaler",StandardScaler())
])

In [80]:
cat_pipeline=Pipeline(steps=[
    ("imputer",SimpleImputer(strategy="most_frequent")),
    ("onehot",OneHotEncoder())
])

In [81]:
Preprocessor=ColumnTransformer([
    ("num_pipeline",num_pipeline,num_features),
    ("cat_pipeline",cat_pipeline,cat_features)
])

In [82]:
Preprocessor

ColumnTransformer(transformers=[('num_pipeline',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaler', StandardScaler())]),
                                 Index(['Restaurant_latitude', 'Restaurant_longitude',
       'Delivery_location_latitude', 'Delivery_location_longitude',
       'Vehicle_condition', 'Hour', 'Minute'],
      dtype='object')),
                                ('cat_pipeline',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('onehot', OneHotEncoder())]),
                                 Index(['Delivery_person_Age', 'Delivery_person_Ratings', 'Weatherconditions',
       'Road_traffic_density', 'Type_of_order', 'Type_of_vehicle',
       'multiple_deliveries', 'Festival', 'City'],
      dtype='object'))])

In [83]:
Preprocessor=Preprocessor.fit(x_train)

In [84]:
Preprocessor

ColumnTransformer(transformers=[('num_pipeline',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaler', StandardScaler())]),
                                 Index(['Restaurant_latitude', 'Restaurant_longitude',
       'Delivery_location_latitude', 'Delivery_location_longitude',
       'Vehicle_condition', 'Hour', 'Minute'],
      dtype='object')),
                                ('cat_pipeline',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('onehot', OneHotEncoder())]),
                                 Index(['Delivery_person_Age', 'Delivery_person_Ratings', 'Weatherconditions',
       'Road_traffic_density', 'Type_of_order', 'Type_of_vehicle',
       'multiple_deliveries', 'Festival', 'City'],
      dtype='object'))])

In [87]:
x_train=Preprocessor.transform(x_train)

In [90]:
x_train=x_train.toarray()

In [97]:
x_train.shape

(36474, 85)

In [92]:
new_data=testing_df.head(1)

In [93]:
new_data

,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,...,multiple_deliveries,Festival,City,Day,Month,Year,Hour,Minute,Pick_Hour,Pick_Minute
0,NaN,NaN,11.003669,76.976494,11.043669,77.016494,conditions NaN,NaN,3,Drinks,...,1,No,Metropolitian,30,3,2022,NaN,NaN,15,5

In [96]:
Preprocessor.transform(new_data).toarray().shape

(1, 85)

In [99]:
import pickle

In [100]:
with open("Preprocessor.pkl","wb") as f:
  pickle.dump(Preprocessor,f)

In [101]:


## here is the as the Preprocessing is done and save the Preprocessor the train new data

In [ ]:
## This is just for checking new data prediction usinng only a model Linear Regression.....

In [102]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [104]:
model.predict(Preprocessor.transform(new_data).toarray())

array([25.97187805])

In [105]:
model.score(x_train,y_train)

0.612651511608256

In [107]:
x_test=Preprocessor.transform(x_test)

In [108]:
model.score(x_test,y_test)

0.6110243862199555

In [111]:
new_data2=training_df.head(1).drop("Time_taken",axis=1)

In [112]:
training_df.head(1)

,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,...,Festival,City,Time_taken,Day,Month,Year,Hour,Minute,Pick_Hour,Pick_Minute
0,37,4.9,22.745049,75.892471,22.765049,75.912471,conditions Sunny,High,2,Snack,...,No,Urban,24,19,3,2022,11.0,30.0,11,45

In [113]:
new_data2

,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,...,multiple_deliveries,Festival,City,Day,Month,Year,Hour,Minute,Pick_Hour,Pick_Minute
0,37,4.9,22.745049,75.892471,22.765049,75.912471,conditions Sunny,High,2,Snack,...,0,No,Urban,19,3,2022,11.0,30.0,11,45

In [114]:
model.predict(Preprocessor.transform(new_data2))

array([19.56970215])

In [115]:
## Need to train our data on the different model ....

In [117]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from sklearn.linear_model import Lasso,Ridge

/usr/local/lib/python3.10/dist-packages/dask/dataframe/__init__.py:42: FutureWarning:
Dask dataframe query planning is disabled because dask-expr is not installed.

You can install it with `pip install dask[dataframe]` or `conda install dask`.
This will raise in a future version.

  warnings.warn(msg, FutureWarning)

In [118]:
models={
    "LinearRegression":LinearRegression(),
    "RandomForestRegressor":RandomForestRegressor(),
    "DecisionTreeRegressor":DecisionTreeRegressor(),
    "XGBRegressor":XGBRegressor(),
    "LGBMRegressor":LGBMRegressor(),
    "Lasso":Lasso(),
    "Ridge":Ridge()
}

In [124]:
list(models.values())[0]

LinearRegression()

In [125]:
def report(models,x_train,y_train,x_test,y_test):
  for i in range(len(models)):
    model=list(models.values())[i]
    model.fit(x_train,y_train)
    y_pred=model.predict(x_test)
    score=model.score(x_test,y_test)
    print(list(models.keys())[i],score)

In [126]:
report(models,x_train,y_train,x_test,y_test)

LinearRegression 0.6110243862199555
RandomForestRegressor 0.7155702127069892
DecisionTreeRegressor 0.45283953220244133
XGBRegressor -18.78998032146561
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003939 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1194
[LightGBM] [Info] Number of data points in the train set: 36474, number of used features: 78
[LightGBM] [Info] Start training from score 26.301612
LGBMRegressor 0.7381375663722011
Lasso 0.15446488238160017
Ridge 0.611053805713206

In [127]:
model1 = RandomForestRegressor()
model1.fit(x_train, y_train)

RandomForestRegressor()

In [128]:
model1.predict(Preprocessor.transform(new_data2))

array([22.62])